name: Slack Stop Motion
on: workflow_dispatch
#   schedule:
#     - cron: "*/20 11-21 * * mon-fri"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x "${GITHUB_WORKSPACE}/slack-stop-motion.sh"
          export TOKEN=${{ secrets.SLACK_TOKEN }}
          "${GITHUB_WORKSPACE}/slack-stop-motion.sh"
