name: Daily Image Update
on:
  schedule:
  - cron: "*/30 7-17 * * mon-fri"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : |
          chmod +x "${GITHUB_WORKSPACE}/slack-stop-motion.sh"
          export TOKEN=${{ secrets.SLACK_TOKEN }}
          "${GITHUB_WORKSPACE}/slack-stop-motion.sh"

